- team/m2/problem.md
> drafted the problem file

- front-end/source/components/AppControllerComponent/AppControllerComponent.js
- front-end/source/components/DynamicSidebarComponent/DynamicSidebarComponent.css
- front-end/source/components/DynamicSidebarComponent/DynamicSidebarComponent.js
I added the sidebar but I still need to add a couple more features and refine the code.
> Added sidebar but it is still not fully implemented

- front-end/source/components/AppControllerComponent/AppControllerComponent.js
- front-end/source/components/DynamicSidebarComponent/DynamicSidebarComponent.css
- front-end/source/components/DynamicSidebarComponent/DynamicSidebarComponent.js
- front-end/source/components/FriendsPageComponent/FriendsPageComponent.js
- front-end/source/components/MainPageComponent/MainPageComponent.css
- front-end/source/components/MainPageComponent/MainPageComponent.js
- front-end/source/components/ProfilePageComponent/ProfilePageComponent.css
- front-end/source/components/ProfilePageComponent/ProfilePageComponent.js
- front-end/source/components/SettingsPageComponent/SettingsPageComponent.js
- front-end/source/index.html
- front-end/source/main.css
I added the page changing through the side bar, made some of the UI and got rid of the task stuff in appcontroller.
> Added page changing feature and got rid of Prof. Richard's task stuff

- front-end/source/components/AboutPageComponent/AboutPageComponent.css
- front-end/source/components/AboutPageComponent/AboutPageComponent.js
- front-end/source/components/MainPageComponent/MainPageComponent.css
- front-end/source/components/MainPageComponent/MainPageComponent.js
Created a static about page that is accessible through the homepage.
> About Page Feature

- front-end/source/components/GearRecComponent/GearRecComponent.css
- front-end/source/components/GearRecComponent/GearRecComponent.js
started on the styling on Gear REC
> gear rec CSS

- front-end/source/components/AddNewTrailComponent/AddNewTrailComponent.css
- front-end/source/components/AddNewTrailComponent/AddNewTrailComponent.js
I added some features like generating message when user successfully added their trails and also automaticall delete all the input when they are finish. Also, I changed the layout of the page to make it nicer
> AddNewTrailComponent

- front-end/source/components/EmergencyContactsComponent/EmergencyContactsComponent.css
- front-end/source/components/EmergencyContactsComponent/EmergencyContactsComponent.js
- front-end/source/components/EmergencyContactsComponent/ben-notes.text
- front-end/source/components/EmergencyContactsInputComponent/EmergencyContactsInputComponent.css
- front-end/source/components/EmergencyContactsInputComponent/EmergencyContactsInputComponent.js
- front-end/source/components/EmergencyContactsListComponent/EmergencyContactsListComponent.css
- front-end/source/components/EmergencyContactsListComponent/EmergencyContactsListComponent.js
I wrote the code for all of the EmergencyContactsComponents. There is a flow that allows users to input emergency contact information in EmergencyContactInputComponent.js, their input then makes its way through eventhub.js until it is accessible by EmergencyContactListComponent.js and is displayed by EmergencyContactComponent.js
> All EmergencyContactsComponents

- front-end/source/eventhub/Events.js
- front-end/source/services/TrailLogService.js
- front-end/tests/trailLogTestSuite.js
Created a service that uses IndexedDB to store data on trail information. Updated Events.JS to keep track of events related to this database. Created a test suite to verify correct functionality.
> TrailLogService

- front-end/source/components/InsightsComponent/InsightsComponent.css
- front-end/source/components/InsightsComponent/InsightsComponent.js
- front-end/source/components/MainPageComponent/MainPageComponent.css
- front-end/source/components/MainPageComponent/MainPageComponent.js
- front-end/source/services/TrailLogService.js
To merge the insights component with main. I added test data to TrailLogService to verify indexedDB functionality, created JS+CSS for insights component and initialized it with test data from the DB. I added this button to the home page.
> 33 insights component

- team/m3/blake-thomas/feature-sequence-diagram.md
- team/m3/features.md
- team/m3/roles.md
Updated and created files necessary for M3.
> Update files blake

- front-end/source/components/EmergencyContactsComponent/ben-notes.text
- front-end/source/components/EmergencyContactsInputComponent/EmergencyContactsInputComponent.js
- front-end/source/components/EmergencyContactsListComponent/EmergencyContactsListComponent.css
- front-end/source/components/EmergencyContactsListComponent/EmergencyContactsListComponent.js
- front-end/source/eventhub/Events.js
- front-end/source/main.js
- front-end/source/services/EmergencyContactsService.js
> 37 implement indexdb for emergencycontacts data

- front-end/source/components/ProfilePageComponent/ProfilePageComponent.css
- team/m3/roles.md
- team/m3/william-hammond/feature-sequence-diagram.md
- team/reports/will-hammond.md
I updated the roles, william-hammond section, added the sequence diagram and made a few other small changes.
> Added in my parts for the documentation

- front-end/source/components/AboutPageComponent/AboutPageComponent.css
- front-end/source/components/AddNewTrailComponent/AddNewTrailComponent.css
- front-end/source/components/AppControllerComponent/AppControllerComponent.js
- front-end/source/components/DarkModeToggleComponent/DarkModeToggleComponent.css
- front-end/source/components/DarkModeToggleComponent/DarkModeToggleComponent.js
- front-end/source/components/EmergencyContactsInputComponent/EmergencyContactsInputComponent.css
- front-end/source/components/EmergencyContactsInputComponent/EmergencyContactsInputComponent.js
- front-end/source/components/FriendsPageComponent/FriendsPageComponent.css
- front-end/source/components/HomeIconComponent/HomeIconComponent.css
- front-end/source/components/InsightsComponent/InsightsComponent.css
- front-end/source/main.css
- front-end/tests/HomeIconComponent.spec.js
Added dark mode toggle feature
> Added dark mode toggle feature

- front-end/source/components/AddNewTrailComponent/AddNewTrailComponent.css
- front-end/source/components/AddNewTrailComponent/AddNewTrailComponent.js
- team/m3/features.md
- team/m3/roles.md
- team/m3/will-palaia/feature-sequence-diagram.md
- team/reports/will-palaia.md
Filled out:
- Commits log
- Features
- roles
- feature sequence diagram
Also put a Google Maps picture in of where I am going to put the widget, setting it up for an easier time with integrating the API in m4.
> Different Logs & Google Maps Set up

- .vscode/.env
- back-end/package-lock.json
- back-end/package.json
- back-end/source/auth/middleware.js
- back-end/source/controller/AuthController.js
- back-end/source/model/User.js
- back-end/source/routes/AuthRoutes.js
- package-lock.json
I added the .env file that should keep the client id and secret private
> Implemented Auth File Structure, Updated Dependencies, and created userModel with Sequelize

- back-end/source/controller/AuthController.js
- back-end/source/routes/AuthRoutes.js
- front-end/source/components/LoginPageComponent/LoginPageComponent.css
- front-end/source/components/LoginPageComponent/LoginPageComponent.js
Implemented the frontend for authentication and added routing for user account deletion. This resolves issues <#80> and <#81>.
> Frontend for Authentication and Account Deletion Feature

- front-end/source/components/AppControllerComponent/AppControllerComponent.js
- front-end/source/components/DynamicSidebarComponent/DynamicSidebarComponent.js
- front-end/source/components/LoginPageComponent/LoginPageComponent.css
- front-end/source/components/LoginPageComponent/LoginPageComponent.js
I added the login page to the sidebar, then I fixed the issue with the button getting all put in the middle of the screen, I added the google authentication button, and added functionality for login, logout, and google buttons.
> <Authentication><#86>:<I added login page to sidebar, and added google button, functionality for some buttons, and a background picture for the page.>

- front-end/source/components/DarkModeToggleComponent/DarkModeToggleComponent.js
Fixed #89 , small edge-case with dark mode and refreshing the page. Fixed it to have proper functionality.
> <Dark Mode><#89>: <Fixed bug with refreshing page in dark mode>

- back-end/.env.example
- back-end/.gitignore 
- back-end/source/Server.js
- back-end/source/config/googlePlaces.js
- back-end/source/controller/PlaceController.js
- back-end/source/routes/PlaceRoute.js
If there is trouble with this merge pay attention to this code in PlaceRoute.js 
router.get('/places/search', async (req, res) => { //figure out what goes in //places/search
await PlaceController.searchPlaces(req, res);
});
/places/search - this needs to be replaced with something that fits front-end
> 91 google places integration

- back-end/source/Server.js
- back-end/source/config/googlePlaces.js
- back-end/source/controller/PlaceController.js
- back-end/source/routes/PlaceRoute.js
Push fixed 91-google-places-integration branch
> Revert 93 91 google places integration

- front-end/source/components/AddNewTrailComponent/AddNewTrailComponent.js
- front-end/source/components/AllTrailComponent/AllTrailComponent.js
- front-end/source/components/AppControllerComponent/AppControllerComponent.js
- front-end/source/components/DynamicSidebarComponent/DynamicSidebarComponent.js
> Create new feature for user to view their added trail

- back-end/source/routes/api/Email.js
- front-end/source/components/CurrentTripComponent/CurrentTripComponent.js
> Current Trip #119: connect current trip info display with all trails
